// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollSaaS.Infrastructure.Persistence;

#nullable disable

namespace PayrollSaaS.Infrastructure.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payroll")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Advances.Advance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("balance_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("GivenDate")
                        .HasColumnType("date")
                        .HasColumnName("given_date");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("installment_amount");

                    b.Property<int>("InstallmentsRecovered")
                        .HasColumnType("integer")
                        .HasColumnName("installments_recovered");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("RecoveryStartMonth")
                        .HasColumnType("date")
                        .HasColumnName("recovery_start_month");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("integer")
                        .HasColumnName("total_installments");

                    b.HasKey("Id")
                        .HasName("pk_advances");

                    b.ToTable("advances", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Advances.AdvanceInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdvanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("advance_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueMonth")
                        .HasColumnType("date")
                        .HasColumnName("due_month");

                    b.Property<Guid?>("PayrollEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_entry_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_advance_installments");

                    b.HasIndex("AdvanceId", "DueMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_advance_installments_advance_id_due_month");

                    b.ToTable("advance_installments", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("EnteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_employee_id_attendance_date");

                    b.ToTable("attendance_records", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date")
                        .HasColumnName("date_of_joining");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employment_status");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ifsc_code");

                    b.Property<DateOnly?>("PfActiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("pf_active_from");

                    b.Property<bool>("PfOptedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("pf_opted_in");

                    b.Property<string>("PfStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pf_status");

                    b.Property<Guid>("SchoolDivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_division_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("staff_name");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("staff_type");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.EmployeePfConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("PfGross")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pf_gross");

                    b.HasKey("Id")
                        .HasName("pk_employee_pf_configs");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_pf_configs_employee_id");

                    b.ToTable("employee_pf_configs", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.EmployeeSalaryComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("component_name");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("component_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_salary_components");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_salary_components_employee_id");

                    b.ToTable("employee_salary_components", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("addition_type");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("PayrollEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_additions");

                    b.HasIndex("PayrollEntryId")
                        .HasDatabaseName("ix_payroll_additions_payroll_entry_id");

                    b.ToTable("payroll_additions", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeductionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("deduction_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("PayrollEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_deductions");

                    b.HasIndex("PayrollEntryId")
                        .HasDatabaseName("ix_payroll_deductions_payroll_entry_id");

                    b.ToTable("payroll_deductions", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AmountMatches")
                        .HasColumnType("boolean")
                        .HasColumnName("amount_matches");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("EsiAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("esi_amount");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_salary");

                    b.Property<decimal?>("HrEnteredAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("hr_entered_amount");

                    b.Property<bool>("IsPfEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pf_eligible");

                    b.Property<int>("LopDays")
                        .HasColumnType("integer")
                        .HasColumnName("lop_days");

                    b.Property<decimal>("LopDeduction")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("lop_deduction");

                    b.Property<decimal>("NettPay")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("nett_pay");

                    b.Property<decimal>("NettSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("nett_salary");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_run_id");

                    b.Property<decimal>("PfGross")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pf_gross");

                    b.Property<decimal>("SalaryAfterPf")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("salary_after_pf");

                    b.Property<decimal>("TotalAdditions")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_additions");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_deductions");

                    b.HasKey("Id")
                        .HasName("pk_payroll_entries");

                    b.HasIndex("PayrollRunId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_entries_payroll_run_id_employee_id");

                    b.ToTable("payroll_entries", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<DateOnly>("PayrollMonth")
                        .HasColumnType("date")
                        .HasColumnName("payroll_month");

                    b.Property<Guid>("SchoolDivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_division_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id")
                        .HasName("pk_payroll_runs");

                    b.HasIndex("SchoolDivisionId", "PayrollMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_runs_school_division_id_payroll_month");

                    b.ToTable("payroll_runs", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schools_tenant_id");

                    b.ToTable("schools", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.SchoolDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_school_divisions");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_school_divisions_school_id_name");

                    b.ToTable("school_divisions", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.SchoolPayrollSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EmployerPfRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("employer_pf_rate");

                    b.Property<decimal>("EsiRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("esi_rate");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_school_payroll_settings");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_school_payroll_settings_school_id");

                    b.ToTable("school_payroll_settings", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("free")
                        .HasColumnName("plan");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "payroll");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Advances.AdvanceInstallment", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Advances.Advance", "Advance")
                        .WithMany("Installments")
                        .HasForeignKey("AdvanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advance_installments_advances_advance_id");

                    b.Navigation("Advance");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.EmployeePfConfig", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Employees.Employee", "Employee")
                        .WithMany("PfConfigs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_pf_configs_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.EmployeeSalaryComponent", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Employees.Employee", "Employee")
                        .WithMany("SalaryComponents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_salary_components_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollAddition", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Payroll.PayrollEntry", "PayrollEntry")
                        .WithMany("Additions")
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_additions_payroll_entries_payroll_entry_id");

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollDeduction", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Payroll.PayrollEntry", "PayrollEntry")
                        .WithMany("Deductions")
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_deductions_payroll_entries_payroll_entry_id");

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollEntry", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Payroll.PayrollRun", "PayrollRun")
                        .WithMany("Entries")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_entries_payroll_runs_payroll_run_id");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.School", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Tenancy.Tenant", "Tenant")
                        .WithMany("Schools")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schools_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.SchoolDivision", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Tenancy.School", "School")
                        .WithMany("Divisions")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_divisions_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.SchoolPayrollSettings", b =>
                {
                    b.HasOne("PayrollSaaS.Domain.Entities.Tenancy.School", "School")
                        .WithOne("PayrollSettings")
                        .HasForeignKey("PayrollSaaS.Domain.Entities.Tenancy.SchoolPayrollSettings", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_payroll_settings_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Advances.Advance", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Employees.Employee", b =>
                {
                    b.Navigation("PfConfigs");

                    b.Navigation("SalaryComponents");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollEntry", b =>
                {
                    b.Navigation("Additions");

                    b.Navigation("Deductions");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Payroll.PayrollRun", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.School", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("PayrollSettings");
                });

            modelBuilder.Entity("PayrollSaaS.Domain.Entities.Tenancy.Tenant", b =>
                {
                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
